# Terraform project for creating NGINX VM in yandex cloud

## Requirements
- terraform
- ansible (version >= 2.5)


## Usage:

### download repo
```
git clone https://github.com/kirgot4-lab/highload-1.git
```

### initialize terraform project
```
terraform init
```

### specify necessary variables

#### credentials:
If you setup yc tool you can symply run .env script:
```
source .env
```

[how to setup yc](https://cloud.yandex.ru/docs/tutorials/infrastructure-management/terraform-quickstart#get-credentials)

or you can specify terraform variables:

```
token
cloud_id
folder_id
```
also you should specify path to ssh keys in *.auto.tfvars file, using for provisioning on created vm

```
ssh_public_key  = 
ssh_privite_key = 
```

ssh keys can be generated by running:
```
ssh-keygen -t ed25519
```

### then apply configuration:

```
terraform apply
```

last string in output should display public URL which opens default nginx page by following it

```
Outputs:

public_ip = "84.201.157.26"
public_url = "http://84.201.157.26"
```
